# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
template-registry-api.json:
  spec:
    - '#/basePath' # Required by I/O Runtime
