application:
  actions: actions
  runtimeManifest:
    packages:
      template-registry-api:
        version: 1.0
        license: Apache-2.0
        inputs: 
          MONGODB_NAME: $MONGODB_NAME
          MONGODB_URI: $MONGODB_URI
        actions:
          templates-post:
            function: actions/templates/post/index.js
            web: "yes"
            runtime: "nodejs:18"
            include:
              - ["template-registry-api.json"]
            inputs:
              LOG_LEVEL: debug
              IMS_URL: $IMS_URL
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              IMS_CLIENT_SECRET: $IMS_CLIENT_SECRET
              IMS_AUTH_CODE: $IMS_AUTH_CODE
              IMS_SCOPES: $IMS_SCOPES
              ACCESS_TOKEN_GITHUB: $ACCESS_TOKEN_GITHUB
              TEMPLATE_REGISTRY_ORG: $TEMPLATE_REGISTRY_ORG
              TEMPLATE_REGISTRY_REPOSITORY: $TEMPLATE_REGISTRY_REPOSITORY
              TEMPLATE_REGISTRY_API_URL: $TEMPLATE_REGISTRY_API_URL
            annotations:
              require-adobe-auth: false
              require-gw-validation: true
              final: true
          templates-put:
            function: actions/templates/put/index.js
            web: "yes"
            runtime: "nodejs:18"
            include:
              - ["template-registry-api.json"]
            inputs:
              LOG_LEVEL: debug
              IMS_URL: $IMS_URL
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              IMS_CLIENT_SECRET: $IMS_CLIENT_SECRET
              IMS_AUTH_CODE: $IMS_AUTH_CODE
              IMS_SCOPES: $IMS_SCOPES
              ACCESS_TOKEN_GITHUB: $ACCESS_TOKEN_GITHUB
              TEMPLATE_REGISTRY_ORG: $TEMPLATE_REGISTRY_ORG
              TEMPLATE_REGISTRY_REPOSITORY: $TEMPLATE_REGISTRY_REPOSITORY
              TEMPLATE_REGISTRY_API_URL: $TEMPLATE_REGISTRY_API_URL
            annotations:
              require-adobe-auth: false
              require-gw-validation: true
              final: true
          templates-get:
            function: actions/templates/get/index.js
            web: "yes"
            runtime: "nodejs:18"
            include:
              - ["template-registry-api.json"]
            inputs:
              LOG_LEVEL: debug
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              TEMPLATE_REGISTRY_ORG: $TEMPLATE_REGISTRY_ORG
              TEMPLATE_REGISTRY_REPOSITORY: $TEMPLATE_REGISTRY_REPOSITORY
              TEMPLATE_REGISTRY_API_URL: $TEMPLATE_REGISTRY_API_URL
            annotations:
              require-adobe-auth: false
              final: true
          templates-delete:
            function: actions/templates/delete/index.js
            web: "yes"
            runtime: "nodejs:18"
            include:
              - ["template-registry-api.json"]
            inputs:
              LOG_LEVEL: debug
              IMS_URL: $IMS_URL
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              ADMIN_IMS_ORGANIZATIONS: $ADMIN_IMS_ORGANIZATIONS
              ACCESS_TOKEN_GITHUB: $ACCESS_TOKEN_GITHUB
              TEMPLATE_REGISTRY_ORG: $TEMPLATE_REGISTRY_ORG
              TEMPLATE_REGISTRY_REPOSITORY: $TEMPLATE_REGISTRY_REPOSITORY
              TEMPLATE_REGISTRY_API_URL: $TEMPLATE_REGISTRY_API_URL
            annotations:
              require-adobe-auth: false
              require-gw-validation: true
              final: true
          templates-list:
            function: actions/templates/list/index.js
            web: "yes"
            runtime: "nodejs:18"
            include:
              - ["template-registry-api.json"]
            inputs:
              LOG_LEVEL: debug
              IMS_URL: $IMS_URL
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              TEMPLATE_REGISTRY_ORG: $TEMPLATE_REGISTRY_ORG
              TEMPLATE_REGISTRY_REPOSITORY: $TEMPLATE_REGISTRY_REPOSITORY
              TEMPLATE_REGISTRY_API_URL: $TEMPLATE_REGISTRY_API_URL
            annotations:
              require-adobe-auth: false
              final: true
          templates-install:
            function: actions/templates/install/index.js
            web: "yes"
            runtime: "nodejs:18"
            include:
              - ["template-registry-api.json"]
            inputs:
              LOG_LEVEL: debug
              IMS_URL: $IMS_URL
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              ACCESS_TOKEN_GITHUB: $ACCESS_TOKEN_GITHUB
              TEMPLATE_REGISTRY_ORG: $TEMPLATE_REGISTRY_ORG
              TEMPLATE_REGISTRY_REPOSITORY: $TEMPLATE_REGISTRY_REPOSITORY
              TEMPLATE_REGISTRY_API_URL: $TEMPLATE_REGISTRY_API_URL
            annotations:
              require-adobe-auth: false
              final: true