name: Deploy API

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options: 
          - stage
          - prod
        default: 'stage'
  release: # Prod
    types: [released]
  push: # Stage
    branches:
      - main

jobs:
  deploy:
    environment: ${{ inputs.environment || github.event_name == 'release' && 'Production' || github.event_name == 'push' && 'Stage' }}
    name: Deploy to ${{ inputs.enviroment || github.event_name == 'release' && 'Production' || github.event_name == 'push' && 'Stage' }}
    # we would like to avoid running this workflow in forked repos
    if: github.repository == 'adobe/adp-template-registry-api'
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['20']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i --package-lock --package-lock-only && npm ci
      - name: Setup Adobe AIO CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          os: ${{ matrix.os }}
          version: 10.x.x
      - name: Generate Template Registry APIs
        env:
          AIO_runtime_auth: ${{ secrets.AIO_RUNTIME_AUTH }}
          AIO_runtime_namespace: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
          AIO_runtime_apihost: ${{ secrets.AIO_RUNTIME_APIHOST }}
        run: aio runtime api create --config-file=template-registry-api.json
      - name: Deploy
        env:
          AIO_runtime_auth: ${{ secrets.AIO_RUNTIME_AUTH }}
          AIO_runtime_namespace: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
          AIO_runtime_apihost: ${{ secrets.AIO_RUNTIME_APIHOST }}
          TEMPLATE_REGISTRY_ORG: ${{ secrets.TEMPLATE_REGISTRY_ORG }}
          TEMPLATE_REGISTRY_REPOSITORY: ${{ secrets.TEMPLATE_REGISTRY_REPOSITORY }}
          ACCESS_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          IMS_URL: ${{ secrets.IMS_URL }}
          IMS_CLIENT_ID: ${{ secrets.IMS_CLIENT_ID }}
          IMS_CLIENT_SECRET: ${{ secrets.IMS_CLIENT_SECRET }}
          IMS_AUTH_CODE: ${{ secrets.IMS_AUTH_CODE }}
          IMS_SCOPES: ${{ secrets.IMS_SCOPES }}
          ADMIN_IMS_ORGANIZATIONS: ${{ secrets.ADMIN_IMS_ORGANIZATIONS }}
          TEMPLATE_REGISTRY_API_URL: ${{ secrets.TEMPLATE_REGISTRY_API_URL }}
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: aio app deploy
